# Generated by Django 4.0.5 on 2022-06-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('contractor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roads.region')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=50)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roads.region')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('road_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=50)),
                ('length', models.FloatField()),
                ('construction_date', models.DateField()),
                ('road_map', models.TextField()),
                ('constructor_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.contractor')),
                ('route_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.route')),
                ('staff_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='roads.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('R', 'routine'), ('P', 'periodic'), ('E', 'emergency')], max_length=20)),
                ('activities', models.CharField(choices=[('CP', 'clearing pavements'), ('SG', 'shoulder grading'), ('PP', 'pothole patching'), ('OV', 'overlay'), ('SD', 'surface dressing'), ('TS', 'traffic signs'), ('DRM', 'debris removal'), ('ACC', 'accident'), ('DRP', 'damage repair')], max_length=20)),
                ('contractor_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.contractor')),
                ('road_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.road')),
                ('staff_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.staff')),
            ],
        ),
    ]
