# Generated by Django 4.0.5 on 2022-06-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='road_status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Ongoing'), ('C', 'Complete')], default='Pending', max_length=15),
        ),
    ]
