# Generated by Django 4.0.5 on 2022-06-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_alter_staff_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='contractor_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.contractor', verbose_name='Contractor'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='road_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.road', verbose_name='Road'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='staff_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.staff', verbose_name='Supervised By'),
        ),
        migrations.AlterField(
            model_name='road',
            name='construction_date',
            field=models.DateField(verbose_name='Construction Date'),
        ),
        migrations.AlterField(
            model_name='road',
            name='constructor_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.contractor', verbose_name='Constructor'),
        ),
        migrations.AlterField(
            model_name='road',
            name='length',
            field=models.FloatField(verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_map',
            field=models.TextField(verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_name',
            field=models.CharField(max_length=50, verbose_name='Road Name'),
        ),
        migrations.AlterField(
            model_name='road',
            name='route_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='roads.route', verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='road',
            name='staff_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='roads.staff', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='region',
            field=models.ForeignKey(default='N/A', null=True, on_delete=django.db.models.deletion.CASCADE, to='roads.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='station',
            field=models.ForeignKey(default='N/A', null=True, on_delete=django.db.models.deletion.CASCADE, to='roads.stations', verbose_name='Station'),
        ),
    ]
