# Generated by Django 4.0.5 on 2022-06-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0005_alter_maintenance_contractor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='roads.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='station',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='roads.stations', verbose_name='Station'),
        ),
    ]
